#!/bin/bash

#
# Re-encodes the given video files with settings appropriate for kartlytics.
#

for file in "$@"; do
	echo "$(date) $file"
	base=$(basename $file)
	root=${base%.*}
	ext=${base##*.}
	newname=$(dirname $file)/$root-small.$ext
	if ! ffmpeg -i $file -b:v 3584k -g 15 $newname > /dev/null 2>&1 ; then
		echo "FAIL"
	else
		mv $file $(dirname $file)/$root-big.$ext
		mv $newname $file
	fi
done
