#!/bin/bash

function fail
{
	echo "$*" >&2
	exit 1
}

function usage
{
	echo "usage: $u_arg0 filename.mov"
	exit 2
}

u_arg0=$(basename $0)

[[ -n "$1" ]] || usage
[[ -f "$1" ]] || fail "not a file: $1"

u_url=http://localhost
u_user=

[[ $# -gt 1 ]] && u_url=$2
[[ $# -gt 2 ]] && u_user="-u$3"

curl $u_user -i -X POST -Ffile=@$1 $u_url/kart/video
