#!/bin/bash

shopt -s xpg_echo

gcm_arg0=$(basename $0)
gcm_maskdir=$1
#gcm_chars="bowser dk luigi mario peach toad wario yoshi"
gcm_chars="bowser"
gcm_kartvid="$(dirname $0)/../out/kartvid"
gcm_nfailed=0

function fail
{
	echo "$*" >&2
	exit 1
}

function softfail
{
	echo "failed"
	(($gcm_nfailed++))
}


[[ -n "$1" && -d "$1" ]] || fail "usage: $gcm_arg0 path/to/masks/dir"
[[ -x $gcm_kartvid ]] || fail "couldn't find executable kartvid at $gcm_kartvid"

for char in $gcm_chars; do
	if ! [[ -f "$gcm_maskdir/char_${char}_1.png" ]]; then
		echo "skipping $char (no mask for square 1)"
		continue
	fi

	echo "Generating char_${char}_2.ppm ... \c "
	$gcm_kartvid translatexy $gcm_maskdir/char_${char}_1.png \
	    $gcm_maskdir/char_${char}_2.ppm 323 0 && echo "done." || softfail

	echo "Converting char_${char}_2.ppm to char_${char}_2.png \c "
	convert $gcm_maskdir/char_${char}_2.ppm \
	    $gcm_maskdir/char_${char}_2.png && \
	    rm -f $gcm_maskdir/char_${char}_2.ppm && echo "done." || softfail

	echo "Generating char_${char}_3.ppm ... \c "
	$gcm_kartvid translatexy $gcm_maskdir/char_${char}_1.png \
	    $gcm_maskdir/char_${char}_3.ppm 0 240 && echo "done." || softfail

	echo "Converting char_${char}_3.ppm to char_${char}_3.png \c "
	convert $gcm_maskdir/char_${char}_3.ppm \
	    $gcm_maskdir/char_${char}_3.png && \
	    rm -f $gcm_maskdir/char_${char}_3.ppm && echo "done." || softfail

	echo "Generating char_${char}_4.ppm ... \c "
	$gcm_kartvid translatexy $gcm_maskdir/char_${char}_1.png \
	    $gcm_maskdir/char_${char}_4.ppm 323 240 && echo "done." || softfail

	echo "Converting char_${char}_4.ppm to char_${char}_4.png \c "
	convert $gcm_maskdir/char_${char}_4.ppm \
	    $gcm_maskdir/char_${char}_4.png && \
	    rm -f $gcm_maskdir/char_${char}_4.ppm && echo "done." || softfail
done

exit $gcm_nfailed
